version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      - /Ibex/node_modules
      - .:/Ibex
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/